import { Metadata } from "next";

type Props = {
  params: Promise<{ productId: string }>;
};

export const generateMetadata = async ({
  params,
}: Props): Promise<Metadata> => {
  const id = (await params).productId;
  return {
    title: `Product ${id}`,
    description:`Information about a PRODUCT ${id}`
  };
};
 87


export default async function ProductDetails({ params }: Props) {
  const productId = (await params).productId;
  return <h1>Details about product {productId}</h1>;
}

// Another example(this should be in the root layout
// export const metadata: Metadata = {
//   title: {
//     default: "Next.js Tutorial – Codevolution",
//     template: "%s | Codevolution",
//   },
//   description: "Generated by Next.js",
// };