import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation"
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
            <title>Majaliwa App Test</title>
          
        </head>
        
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className ="text-center">
            <h1 style={{ color: "purple", fontSize: "18px" ,backgroundColor:"white"}}>Majaliwa App Test</h1>
            <h2 style={{ backgroundColor:"white",color: "purple"}}>
              <Navigation/>
            </h2>
            <br />
          </header>
          
          {children}
          <footer className ="text-center">
            <br />
            <p style={{ color: "purple", fontSize: "13px" ,backgroundColor:"white"}}>Powered by Majaliwa LTD</p>
          </footer>
        </body>
        
      </html>

    </ClerkProvider>
    
  );
}
